image:
  name: swedishembedded/build:v0.26.4-1

default:
  tags:
    - docker

cache:
  key: $CI_COMMIT_REF_SLUG

stages:
  - build
  - unit_tests
  - integration_tests
  - system_tests

# This job runs all code checks, unit and integration tests
integrity:
  stage: build
  artifacts:
    paths:
      - report.html
      - log.html
    expire_in: 1 week
    when: always
  script:
    - ./scripts/init
    - ./scripts/check
    - pre-commit run --all-files

# This job builds applications
documentation:
  stage: build
  artifacts:
    paths:
      - build-doc/**/*.pdf
    expire_in: 1 week
    when: always
  script:
    # for docs. Move to docker image.
    - apt-get update && apt-get install -qy tex-gyre
    - ./scripts/init
    - ./scripts/build-doc --sdk-only

applications:
  stage: build
  artifacts:
    paths:
      - build-apps/**/zephyr.elf
      - build-release/**/release/
      - release/*
    expire_in: 1 week
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build-tests/coverage.xml
      junit:
        # Report from unit and integration testing
        - build-tests/twister_report.xml
  script:
    - ./scripts/init
    - ./scripts/build

# This job runs all system tests on built applications
test:
  stage: unit_tests
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    paths:
      - build-tests/coverage*
    expire_in: 1 week
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build-tests/coverage.xml
      junit:
        # Report from unit and integration testing
        - build-tests/twister_report.xml
  script:
    - ./scripts/init
    - ./scripts/test
