# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-getting-started

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.0.0
      import: true
    - name: cmock
      path: modules/test/cmock
      revision: f65066f15d8248e6dcb778efb8739904a4512087
      remote: throwtheswitch
    - name: unity
      path: modules/test/cmock/vendor/unity
      revision: 1958b977019c3ac19bb83350f7b26e60cbeb6c75
      remote: throwtheswitch
