# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: sdk
    west-commands: scripts/west-commands.yml

  remotes:
    - name: swedishembedded
      url-base: https://github.com/swedishembedded
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: renode
      url-base: https://github.com/renode
  projects:
    - name: workstation
      remote: swedishembedded
      revision: v0.26.4-0
      path: workstation
    - name: zephyr
      remote: zephyr
      revision: v3.4.0
      import: true
    - name: renode
      path: tools/renode
      revision: v1.13.1
      submodules: true
      remote: renode
    - name: renode-docs
      path: tools/renode/docs
      revision: master
      remote: renode
    - name: control
      path: modules/lib/control
      revision: v0.36.0
      remote: swedishembedded
    - name: instruments
      path: tools/instruments
      revision: v0.35.1
      remote: swedishembedded
    - name: testing
      path: modules/test/testing
      revision: fc85f31
      remote: swedishembedded
      import: true
